feature 모듈 생성
duckie-team/duckie-android pull request #103
Opened 2022-12-01 15:21 UTC by EvergreenTree97

## Overview (Required)
공통적으로 사용되는 플러그인과, 의존성을 추가하였습니다.
필요에 따라 추가해서 사용하면 될 것 같습니다.

2022-12-01 16:30 UTC, jisungbin commented
👀

2022-12-01 17:40 UTC, jisungbin requested changes

2022-12-01 17:40 UTC, jisungbin commented on feature-ui-create-problems/build.gradle.kts
> +    namespace = "team.duckie.app.android.feature.create.problems.screen"
```suggestion
    namespace = "team.duckie.app.android.feature.ui.create.problems"
```

2022-12-01 17:40 UTC, jisungbin commented on feature-ui-create-problems/build.gradle.kts
> +dependencies {
꼭 필요한 의존성들은 이미 플러그인에서 다 추가됩니다.
당장 사용하지 않을 의존성들을 지워주세요. 이렇게 하면 추후 사용하지 않는 의존성들까지 포함하여 앱을 빌드하게 됩니다.

2022-12-01 17:40 UTC, jisungbin commented on feature-ui-create-problems/src/androidTest/java/com/yapp/feature_ui_create_problems/ExampleInstrumentedTest.kt
> +package com.yapp.feature_ui_create_problems
패캐지명 namepsace 와 맞춰주세요

2022-12-01 17:40 UTC, jisungbin commented on feature-ui-create-problems/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
코드 정렬 부탁드려요
`ctrl + alt + l`

2022-12-01 17:40 UTC, jisungbin commented on feature-ui-create-problems/src/androidTest/java/com/yapp/feature_ui_create_problems/ExampleInstrumentedTest.kt
> +package com.yapp.feature_ui_create_problems
`java` 패키지을 `kotlin` 으로 바꿔주세요

2022-12-01 17:40 UTC, jisungbin commented on settings.gradle.kts
> +    ":feature-ui-solving-problems",
```suggestion
    ":feature-ui-solve-problem",
```

2022-12-01 17:40 UTC, jisungbin commented on settings.gradle.kts
> +    ":feature-ui-create-problems",
```suggestion
    ":feature-ui-create-problem",
```

2022-12-01 17:40 UTC, jisungbin commented on settings.gradle.kts
> +    ":feature-ui-home",
```suggestion
```

중복됩니다.

2022-12-01 17:41 UTC, jisungbin commented
작업 수고하셨습니다. 추가해 주신 모듈들에 모두 리뷰가 중복되어 한 모듈에만 리뷰를 달았습니다. 추가하신 모든 모듈들에 동일하게 리뷰를 반영해 주시면 됩니다.

2022-12-02 06:09 UTC, EvergreenTree97 commented on feature-ui-create-problems/src/androidTest/java/com/yapp/feature_ui_create_problems/ExampleInstrumentedTest.kt
> +package com.yapp.feature_ui_create_problems
java 패키지를 kotlin으로 변경하면 좋은 점이 있나요??

2022-12-02 06:11 UTC, EvergreenTree97 commented
변경 사항 적용했습니다 확인하시면 머지하고 브랜치 삭제할게요

2022-12-02 10:02 UTC, jisungbin approved these changes

2022-12-02 10:04 UTC, jisungbin commented on feature-ui-create-problems/src/androidTest/java/com/yapp/feature_ui_create_problems/ExampleInstrumentedTest.kt
> +package com.yapp.feature_ui_create_problems
아니요 그냥 저희가 코틀린 쓰니깐요

2022-12-02 10:25 UTC, merged