문제 만들기 API 호출
duckie-team/duckie-android pull request #105
Opened 2022-12-06 15:30 UTC by EvergreenTree97

## Overview (Required)
DI 
-  Ktor Client를 주입할 수 있는 Module 생성
-  Repository, Usecase Modeul 생성

Data
- model, repository, datasource 작성

Domain
- Usecase 작성

Presentation
- ui-create-problem 모듈에 viewModel로 더미 데이터 받아올 수 있도록 작성

## TODO
![image](https://user-images.githubusercontent.com/70064912/205954083-cdf9ca0f-196b-4d15-a280-efa81975547f.png)

2022-12-06 15:50 UTC, riflockle7 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamRequest.kt
> +    val title: String,
저희 json 직렬화 라이브러리 `jackson` 쓰기로 했을까요?

jackson 이 긍정적 이야기가 많이 오갔던 것 같은데, 
픽스가 되었는지는 기억이 약간 가물가물하네요

2022-12-06 15:50 UTC, riflockle7 commented on gradle/libs.versions.toml
> +plugin-build-gradle-android = "8.0.0-alpha09"
요거는 아래 `google-service` 버전이 올라가면서 같이 수정된 걸까요?

2022-12-06 16:11 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamResponse.kt
> +    val updatedAt: Date,
이부분도 아직 서버 Response 형식이 확립되지 않아서 Date로 처리했습니다 추후에 변경하겠습니다!

2022-12-06 16:16 UTC, riflockle7 commented on gradle/libs.versions.toml
> +plugin-build-gradle-android = "8.0.0-alpha09"
build 나 run 은 되었었죠?

카나리 버전하고 꼬일까 생각이 들어서 comment 를 남겼었는데
별 문제 없었다면 저대로 해도 될 거 같네요

2022-12-06 17:01 UTC, EvergreenTree97 commented on gradle/libs.versions.toml
> +plugin-build-gradle-android = "8.0.0-alpha09"
네넵 빌드 run 잘 됩니다!
혹시라도 안된다면 [이것](https://github.com/duckie-team/duckie-android#build-prerequisites)이 안되어 있을 확률이 높습니다

2022-12-06 23:13 UTC, jisungbin requested changes
작업 수고하셨습니다.

2022-12-07 01:23 UTC, riflockle7 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamRequest.kt
> +    val title: String,
> https://sungbinland.slack.com/archives/C043MKB4TJN/p1670367290590129?thread_ts=1668173871.352529&cid=C043MKB4TJN

jackson 사용함

2022-12-07 06:11 UTC, EvergreenTree97 commented on gradle/libs.versions.toml
> +plugin-build-gradle-android = "8.0.0-alpha09"
> 요거는 아래 google-service 버전이 올라가면서 같이 수정된 걸까요?
agp 자동 업데이트가 설정되어서 agp 버전이 올라가고, google service 버전을 올렸네요!
버전 관리가 미흡하여 혼동을 드렸던 것 같습니다😥

https://sungbinland.slack.com/archives/C043MKB4TJN/p1668173871352529
Canary 8로 다운그레이드 하고, 버전도 롤백 시켜놓겠습니다!

2022-12-07 06:14 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
> +fun ExamParam.toData() = ExamRequest(
아녀 internal 명시를 안했네요 수정하겠습니다

2022-12-07 06:18 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamResponse.kt
> +    val buttonTitle: String,
![image](https://user-images.githubusercontent.com/70064912/206102849-3d7d994d-d95d-4324-a74c-029b53206f8f.png)
해당 프로퍼티가 덕질고사 시작 버튼 텍스트를 의미해서 그대로 사용해도 괜찮지 않을까요? 
서버에서 내려주는 response 요소 중 하나기도 하니까요

2022-12-07 06:26 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamResponse.kt
> +data class ExamResponse(
Jackson 한정 empty constructor가 필요하군요

2022-12-07 10:29 UTC, merged