GalleryRepository DI 적용 및 ktlint, detekt 검출된 사항 수정
duckie-team/duckie-android pull request #108
Opened 2022-12-07 14:48 UTC by EvergreenTree97

## Issue

- close #93 

## Overview (Required)
GalleryRepository DI 적용하고, KakaoRepository는 assistedInject로 주입
./gradlew build시 적용되는 정적 분석 도구들 통과
Hilt binds에 필요한 abstract class에서  [UnnecessaryAbstractClass] 이 검출되어 **workflow 설정 변경**

2022-12-07 14:57 UTC, jisungbin requested changes
작업 수고하셨습니다.

2022-12-07 15:22 UTC, jisungbin commented on .gitignore
> +/.idea/codeStyles
이거는 왜 취소하셨을까여?
같은 프로젝트에서 코드 스타일은 공유해야 하니 의도된 부분입니다.

2022-12-07 15:22 UTC, jisungbin commented on data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
> +        Log.d("exampleRequest", examRequest.toString())
nit: 안드로이드 의존성을 추가하지 않는 `println` 을 사용하는 건 어떨까요?

2022-12-07 15:22 UTC, jisungbin commented on di/src/main/kotlin/team/duckie/app/android/di/repository/ExamRepositoryModule.kt
> +@file:Suppress("UnnecessaryAbstractClass")
상단에 newline 해주세요

2022-12-07 15:28 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
> +        Log.d("exampleRequest", examRequest.toString())
동의합니다 변경하는 김에 바꿔놓을게요

2022-12-07 16:07 UTC, jisungbin approved these changes

2022-12-07 16:08 UTC, merged

2022-12-10 15:47 UTC, riflockle7 commented on data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
> +        Log.d("exampleRequest", examRequest.toString())
저거 print 로 하면 release 앱에서도 나오지 않나요?

2022-12-10 15:49 UTC, jisungbin commented on data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
> +        Log.d("exampleRequest", examRequest.toString())
아 맞다 
로깅 모듈을 따로 만들어서 나중에 println 을 다 교체하는 식으로 하면 좋겠네요