덕질고사 홈 화면 UI
duckie-team/duckie-android pull request #112
Opened 2022-12-16 07:00 UTC by limsaehyun

## Overview (Required)
- 덕질고사 홈 화면을 구현하였습니다.
- 수정이 필요한 컴포넌트들은 TODO처리 해두었습니다.
- coil과, pager 의존성을 추가했습니다.
- 더미 데이터를 이용해 UI를 위주로 작업했습니다.
- 아직 미숙하여 거침없는 리뷰 부탁드립니다!

### 참고
* 메인 화면의 하단 패딩은 혜진님과 [상의](https://sungbinland.slack.com/archives/C03CM18M529/p1671172894108729) 끝에 약간의 변경이 있습니다.
* 폰트 이슈가 있어 고려해주시면 감사하겠습니다.

## Screenshot

<img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/80076029/208040728-d99af315-11f0-4772-981f-d70665fa4f85.png" width="300" />
<img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/80076029/208040835-a26a339b-353d-4208-b5e6-a7e3dfc2fd3c.png" width="300" />

2022-12-17 05:12 UTC, jisungbin requested changes
일단 여기서 한 번 끊겠습니다.
여기까지 리뷰 반영해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +internal data class Maker(
이런 비즈니스 로직과 관련된 코드엔 문서화 부탁드려요.
그리고 필드명과 실제 필드의 의미가 불일치해 보입니다.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    val cover: String,
```suggestion
    val coverUrl: String,
```

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    val name: String,
name 과 profile 이 같은 유저 객체에서 나올 것으로 보이는데, 좀 더 유연하게 `val owner: User` 같이 제공하고 해당 필드에서 값을 가져오는 건 어떨까요?

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    val takers: Int,
```suggestion
    val takerNumber: Int,
```

takers 라 하면 시험에 응시한 유저 객체를 의미하는 것으로 보입니다.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    val users: PersistentList<RecommendUser>,
ImmutableList 사용해 주세요.
값 수정이 일어나지 않는 상황에선 PersistentList 보단 ImmutableList 가 적합합니다.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    val userId: Int = 0,
userId 에 기본값을 지정하신 이유가 있나요? uuid 로 보여 겹치면 안될 값으로 예상됩니다.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +private val HomeFollowingPadding: Dp = 24.dp
직접 타입을 명시하신 이유가 있나요?
타입을 명시한 순간부터 명시한 타입도 유지보수 범위에 들어오기에, 저는 최대한 smart-casting 에 의지하는 편이 좋다고 생각합니다.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +                Spacer(modifier = Modifier.height(HomeFollowingPadding))
horizontalAlignement 의 spacedBy 를 이용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +            Spacer(modifier = Modifier.height(16.dp))
마지막 항목엔 패딩이 없을 것으로 예상됩니다.
horizontalAlignement 의 spacedBy 를 이용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    Spacer(modifier = Modifier.height(24.dp))
`Modifier.padding` 을 사용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    Spacer(modifier = Modifier.height(12.dp))
`Modifier.padding` 을 사용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    recommendUser.map { user ->
fastForEach 를 사용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    Spacer(modifier = Modifier.height(16.dp))
`Modifier.padding` 을 사용해 주세요.

2022-12-17 05:12 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +        RecommendUserProfile(
다 User 로 부터 나오는 필드는 일일이 개별 필드로 받지 말고, User 객체 자체를 받게끔 하는 편이 어떨까요?
추후 활용성 측면에서 이 방법이 훨씬 유연하다고 저는 생각합니다.

2022-12-17 05:12 UTC, jisungbin commented
작업 수고하셨어요! 나머지 범위는 지금까지의 리뷰 반영된 후에 리뷰 진행할게요.

2022-12-17 08:09 UTC, EvergreenTree97 reviewed
고생하셨습니다! 
컨벤션 관련해서 전체적으로 수정이 필요해 보입니다!

2022-12-17 08:09 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +private val HomeFollowingPadding: Dp = 24.dp
+ 개발자가 타입을 유추하기 쉽지 않은 경우에 명시해주곤 하는데, 해당 경우에는 Padding이라는 네이밍 뿐더러 .dp에서 쉽게 유추할 수 있을 듯 해요!

2022-12-17 08:09 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +        items(recommendCategories) { categories ->
고유 키가 있다면 key = 를 지정해주는 것이 성능 향상에 도움될 것 같습니다

2022-12-17 08:18 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
> +internal data class HomeRecommendItem(
아직 Data들이 ViewModel에 이전되지 않은 상태일까요?
이런 데이터들이 HomeState의 상태 안에서 관리되고, ViewModel의 비즈니스 로직을 통해 관리되어야 할 것 같아서요!

2022-12-17 08:18 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
> +    val state = vm.state.collectAsStateWithLifecycle().value
저희 LocalViewModel을 사용하고 있어서 vm을 인자로 받지 않고 LocalViewModel.current as HomeViewModel로 사용할 수 잇을 것 같아요

2022-12-17 08:18 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +data class HomeState(
View에 있던 data class를 ViewModel로 옮기면서 전체적인 상태 정의가 필요해 보여요!
홈 화면에서는 Loading 상태도 존재할 것 같고, 그에 따른 error 상태도 존재할 것 같아요
각각의 상태를 정의하고, 그에 따른 데이터들을 클래스로 묶어서 관리하면 어떨까요?

2022-12-17 09:00 UTC, jisungbin approved these changes

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/DuckTestBottomNavigation.kt
> +    val IconSize = DpSize(
argument 1개일 경우 한 줄 처리, 그 이상일 경우 여러줄 처리로 알고 있어요
혹시 이거 맞을까요? 🙏

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/RecommendUserProfile.kt
> +    takers: Int,
순간 tester 도 생각했었는데, 지금 저희 앱이 exam 용어를 많이 사용해서 저도 `examinee` 가 좋아보입니다 👍

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +private val HomeFollowingPadding: Dp = 24.dp
개인적으로는 변수명 뒤에 `Dp` 를 붙여주면 좋을 것 같네요. 변수명 만으로도 빠른 타입 캐치가 가능해보여서요.

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
> +    val state = vm.state.collectAsStateWithLifecycle().value
https://github.com/duckie-team/duckie-android/pull/110#discussion_r1045266810

위 comment 를 참고하시면 도움이 될 것 같습니다.

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
> +                // TODO
`TODO(작성자id): 내용`

2022-12-17 10:33 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
> +
두 개 컴포저블만 있는 듯 하네요
`horizontalArrangement = Arrangement.SpaceBetween` 를 추가하면  
`Spacer(modifier = Modifier.weight(1f))` 를 없앨 수 있습니다.

(저도 성빈님 통해서 알았네요 👍)

2022-12-19 00:32 UTC, limsaehyun commented on feature-ui-home/build.gradle.kts
> +        libs.compose.ktx.lifecycle,
`libs.ktx.lifecycle`을 제거하겠습니다. 감사해요

2022-12-19 00:35 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/DuckTestBottomNavigation.kt
> +internal fun DuckTestBottomNavigation(
꽥꽥에 있는 컴포넌트는 덕키를 위한 컴포넌트이고 따라서 아이콘같은 부분이 달랐어요.
그래서 덕질고사를 위한 BottomNavigation을 따로 만들었습니다.

2022-12-19 00:35 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/HomeTextTab.kt
> +@Composable
네 맞습니다.

2022-12-19 00:46 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/RecommendUserProfile.kt
> +internal fun RecommendUserProfile(
해당 화면은 `HomeRecommendScreen` 이고
찾아보신 `RecommendUserProfile` 유저 프로필에 관련한 내용이에요.
네이밍에 혼동이 있네요. 수정해보겠습니다

2022-12-19 05:18 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +                Spacer(modifier = Modifier.height(HomeFollowingPadding))
spacedBy를 사용했습니다. 하지만 spacedBy가 마지막 요소에는 적용되지 않아. index가 마지막일 경우에만 Padding을 따로 두었습니다.
마지막에도 Padding을 줄 수 있는 다른 좋은 방법이 있을까요?

2022-12-19 05:44 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/HomeTextTab.kt
> +
사실 이 TextTab이 이 상황 말고도 다양한 곳에서 활용될 수 있다고 생각했어요.
그래서 여러 상황에서 대응할 수 있게 제목들을 인자로 받고 이러한 형식으로 코드를 작성했어요.
혹시 원하시는 답변이 맞을까요? (잘못 이해한 것 같기도 하네요)

2022-12-19 05:45 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/RecommendUserProfile.kt
> +    takers: Int,
`examinee` 로 픽스하겠습니다!

2022-12-19 05:55 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/RecommendUserProfile.kt
> +                text = "${stringResource(id = R.string.taker)} $takers  ·  $createAt",
음.. `text = stringResource(id = R.string.taker, takers, createAt) ` 해당 코드로 작성해보았는데 `takers`, `createAt` 정보가 보이지 않습니다. 코드가 정확한가요?

2022-12-19 06:01 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
> +internal data class HomeRecommendItem(
아직 Data들이 ViewModel에 이전되지 않은 상태입니다.
이 PR Merge 후에 말씀주신대로 개선 예정입니다!

2022-12-19 06:14 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +data class HomeState(
사실 이번 PR에서는 UI 구현을 목표로 했어요.
그래서 아직 Data들이 ViewModel에 이전되지 않은 상태입니다.

다시 생각해보니 이 부분까지 이번 PR에서 해당 부분까지 처리하면 좋을 것 같네요.
다른 comment부터 fix하고 고쳐보겠습니다 :)

2022-12-19 06:23 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/HomeTextTab.kt
> +
재사용성에 대해서는 충분히 만족하고 계신 것 같습니다!
다만 Row로 구현할 수 있는 것을 LazyRow로 구현하였다면, LazyRow의 성능 향상을 기대할 수 있는 key 속성을 제공하는 것이 어떨까 싶습니다!

2022-12-19 06:24 UTC, limsaehyun commented
아레 comment를 제외하고 모두 반영하였습니다.

https://github.com/duckie-team/duckie-android/pull/112#discussion_r1051359339
https://github.com/duckie-team/duckie-android/pull/112#discussion_r1051317234
https://github.com/duckie-team/duckie-android/pull/112#discussion_r1051358743

원래 UI만을 작업하는 PR이었는데 말씀주셨던 부분까지 신경을 써야 할 것 같아서
PR 목표를 "UI 구현 & VM과 기타 상태 관리 & KDoc 작업"로 바꾸려고 해요.
작업 후 ReRequest 드리겠습니다!
(리뷰는 계속해서 진행해주셔도 괜찮아요)

2022-12-19 06:26 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/common/RecommendUserProfile.kt
> +                text = "${stringResource(id = R.string.taker)} $takers  ·  $createAt",
아아 string.xml에서 `<string name = "taker">%s %s · %s</string> ` 로 정의하여 %s를 stringResource의 vararg로 제공할 수 있습니다

2022-12-19 06:58 UTC, riflockle7 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +data class HomeState(
@EvergreenTree97 @limsaehyun

이전에 이야기했다시피 PR 이 무거워집니다.
일단은 UI 관련된 작업만 진행하시고 다음 PR 에서 진행하시죠

2022-12-19 06:59 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +data class HomeState(
저도 다음부터는 세현님 방식처럼 PR 단위를 조금 줄여보겠습니다

2022-12-19 07:08 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +data class HomeState(
락스님의 조언대로 PR 단위가 무거워질 수 있고 PR이 계속 open되어 있기에 위 comment는 다음 PR 에서 다루도록 하겠습니다!

2022-12-19 14:01 UTC, EvergreenTree97 approved these changes

2022-12-20 04:33 UTC, riflockle7 approved these changes

2022-12-20 04:34 UTC, merged