Feat/홈 UI fix & SearchResult UI 작업
duckie-team/duckie-android pull request #127
Opened 2023-01-02 11:42 UTC by limsaehyun

## Overview (Required)
- 홈 UI 재구성
- 데이터를 VM에서 관리하도록 이전
- 홈 Recommendations 페이징 적용
- SearchResult UI 작업

### 참고
*.SearchResult에도 페이징이 필요합니다. 페이징이 아직 미숙하여 Approve된다면 비즈니스 로직 작업 시 같이 진행하겠습니다.

## Screenshot

<img width="300" alt="image" src="https://user-images.githubusercontent.com/80076029/210226053-4d943387-3ed0-4fca-9b5a-c75f8dec5216.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/80076029/210226105-5ea859a8-282c-4360-8113-1044a2f0f357.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/80076029/210226609-26175d76-bd49-4239-9070-c61175148634.png">
HomeHorizontalPadding
<img width="300" alt="image" src="https://user-images.githubusercontent.com/80076029/210226678-6202dc1a-44da-4bf0-b117-da5988d0e3ba.png">

2023-01-02 15:38 UTC, jisungbin commented
```
/data/recommendation/paging/RecommendationPagingSource.kt: (29, 25): Unresolved reference: 요3
```

빌드 에러 확인 부탁드려요.

2023-01-02 15:38 UTC, jisungbin commented
PR 올리시기 전에 `./gradlew build` 꼭꼭 부탁드려요 제발.
CI 시간 제한있어서 다 쓰면 유료 플랜으로 올려야 합니다.

2023-01-02 15:47 UTC, EvergreenTree97 reviewed
고생하셨습니다

2023-01-02 15:47 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/recommendation/model/RecommendationsResponse.kt
> +data class RecommendationsResponse(
추후 Response DTO로 이용되기 위해서는, null 처리와 JsonProperty Annotation이 필요할 것 같은데 API 작업 때 추가될까요?

2023-01-02 15:47 UTC, EvergreenTree97 commented on data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
> +    override suspend fun fetchInitRecommendations() {
InitRecommendation이랑 Recommendations의 차이가 무엇인지 알 수 있을까여

2023-01-02 15:47 UTC, EvergreenTree97 commented on di/src/main/kotlin/team/duckie/app/android/di/usecase/recommendation/FetchRecommendFollowingUseCaseModule.kt
> +object FetchRecommendFollowingUseCaseModule {
Repository 단위로 패키지를 선언하고 한 모듈에 Provider를 관리하는건 어떨까요?
`RecommendationRepository`

2023-01-02 15:47 UTC, EvergreenTree97 commented on domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/model/RecommendationFeeds.kt
> +data class RecommendationFeeds(
```
@Immutable
```
어노테이션이 빠졌습니다!

2023-01-02 15:47 UTC, EvergreenTree97 commented on domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchRecommendationsUseCase.kt
> +    fun init() = kotlin.runCatching {
```suggestion
    fun init() = runCatching {
```

2023-01-02 15:47 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
> +                        isHomeFollowingTestLoading = false,
```
prevState.copy(
    recommendFollowingTest = DummyRecommendFollowerTest,
    isHomeFollwingTestLoading = false,
)
```
로 가져가는것은 어떨까요?

2023-01-02 15:47 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/sideeffect/HomeSideEffect.kt
> +    class ReportError(val exception: Throwable) : HomeSideEffect()
저희 FirebaseCrashlystics에 예외 보내는거 네트워크 호출하는 모든 경우에 해야하는건가요?

2023-01-02 15:47 UTC, EvergreenTree97 commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
> +    val jumbotrons: PersistentList<HomeRecommendJumbotron> = persistentListOf(),
```suggestion
    val jumbotrons: ImmutableList<HomeRecommendJumbotron> = persistentListOf(),
```

2023-01-03 00:08 UTC, limsaehyun commented on data/src/main/kotlin/team/duckie/app/android/data/recommendation/model/RecommendationsResponse.kt
> +data class RecommendationsResponse(
현재 API 명세가 불안정한 상황이라 말씀주신 내용이 맞습니다!

2023-01-03 00:10 UTC, limsaehyun commented on data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
> +    override suspend fun fetchInitRecommendations() {
아 네이밍을 수정했습니다.
Init은 홈 추천 페이지가 처음 생겼을 때 Jumbotron과 추천 피드에 대한 정보를 가져옵니다.
recommdandtions는 2페이지부터 사용되는 추천 피드 PagingSource를 가져옵니다.

fetchInitRecommendations을 `fetchJumbotrons` 로 명명하겠습니다.

2023-01-04 02:26 UTC, limsaehyun commented on di/src/main/kotlin/team/duckie/app/android/di/usecase/recommendation/FetchRecommendFollowingUseCaseModule.kt
> +object FetchRecommendFollowingUseCaseModule {
반영하겠습니다!

2023-01-04 02:30 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/sideeffect/HomeSideEffect.kt
> +    class ReportError(val exception: Throwable) : HomeSideEffect()
저는 네트워크 호출의 경우에는 예상하지 못하는 오류가 발생할 수 있다고 생각해서 그렇다고 생각합니다.

2023-01-04 02:33 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
> +                        isHomeFollowingTestLoading = false,
이 부분은 pr이 무거워지는 것 같아 추후에 로딩처리 개선 할 때 같이 개선하겠습니다!

2023-01-05 07:27 UTC, jisungbin requested changes

2023-01-05 07:27 UTC, jisungbin commented on data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
> +    private val context: Context,
rest api crud 만 있는 repository 에서 context 가 필요할까요?

2023-01-05 07:27 UTC, jisungbin commented on domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/model/RecommendationFeeds.kt
> +    val recommendations: List<Recommendation>,
ImmutableList 로 받아주세요.

2023-01-05 07:27 UTC, jisungbin commented on domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/model/SearchType.kt
> +    USER,
상수 표기법 낙타로 합의했습니다.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/HomeTopAppBar.kt
> +    val homeTextTabTitles = persistentListOf(
1. remember 처리 해주세요.
2. ImmutableList 로 해주세요.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/BottomNavigationStep.kt
>  enum class BottomNavigationStep(
접근제한자 고려 된걸까요?

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/HomeStep.kt
> +enum class HomeStep(
접근제한자 고려 된걸까요?

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +        AnimatedVisibility(visible = state.isHomeFollowingTestLoading) {
QuackAnimatedVisibility 써주세요.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
> +    recommendUser: List<HomeState.RecommendUserByTopic.User>,
ImmutableList 로 받아주세요.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
>  import com.google.accompanist.pager.rememberPagerState
pager 컴포즈 알파에 공식 지원합니다. 반영이 안됐길래 다시 말씀드려요.
외부 의존성 사용 자제해 주세요.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
> +                    title = item!!.title,
item 이 왜 nullable 하나요?
그리고 `!!` 는 사용하지 말아주세요. 매우 위험한 방법입니다.
smart-casting 이나 null-assertion 으로 대체해야 합니다.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
> +    exams: PersistentList<RecommendationFeeds.Recommendation.Exam>,
`PersistentList` 와 `ImmutableList` 의 차이점을 알고 계시나요?
적어도 내가 사용하고자 하는 코드의 의미는 알고 사용해야 한다고 생각합니다.
모르시고 사용하는거 같아서 말씀드려요. 아니라면 죄송합니다.

(지난번에도 `PersistentList` 와 `ImmutableList` 짚어드린 거 같은데, 반영이 안됐길래 다시 말씀드려요.)

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
> +                        isHomeFollowingInitialLoading = false,
`isHomeFollowingInitialLoading` 상태가 필요할까요?
`recommendFollowing` 상태값 하나로 다 해결 가능해 보입니다.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/sideeffect/HomeSideEffect.kt
> +    class ReportError(val exception: Throwable) : HomeSideEffect()
> 저희 FirebaseCrashlystics에 예외 보내는거 네트워크 호출하는 모든 경우에 해야하는건가요?

네트워크 호출뿐만 아니라 모든 예외에서 진행해야 합니다. 그래야 저희가 예외를 파악하고 대응할 수 있어요.

2023-01-05 07:27 UTC, jisungbin commented on feature-ui-search/build.gradle.kts
> +dependencies {
사용하시는 플러그인과 의존성만 추가하신게 맞나요?

2023-01-05 07:28 UTC, jisungbin commented
간단하게(중요하게 생각되는 부분만) 리뷰 마쳤습니다. 작업 수고하셨어요.

2023-01-06 02:11 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/BottomNavigationStep.kt
>  enum class BottomNavigationStep(
네 맞습니다 internal 처리를 시도했으나 VM에서 step을 바꾸는 과정에서 오류가 나서 public처리 하였습니다.

2023-01-06 03:21 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
> +    exams: PersistentList<RecommendationFeeds.Recommendation.Exam>,
이번 기회에 공부 좀 해봐야겠네요.
조언 감사합니다!

2023-01-06 04:43 UTC, limsaehyun commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
> +                        isHomeFollowingInitialLoading = false,
홈에 있는 로딩을 상위 컴포저블에서 `isHomeLoading`으로 처리하겠습니다!

2023-01-06 06:40 UTC, jisungbin commented on feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/BottomNavigationStep.kt
>  enum class BottomNavigationStep(
> 네 맞습니다 internal 처리를 시도했으나 VM에서 step을 바꾸는 과정에서 오류가 나서 public처리 하였습니다.

ViewModel 도 internal 로 하셨나요?

2023-01-06 06:43 UTC, jisungbin commented
@limsaehyun conflict 해결해 주세요.

2023-01-07 03:58 UTC, limsaehyun commented
@jisungbin internal 및 build success 처리 완료했습니다!

2023-01-07 05:02 UTC, riflockle7 approved these changes
동작되는 내용 확인했습니다. 수고하셨습니다

2023-01-07 19:35 UTC, merged