스플래쉬, 로그인, 온보딩 화면 구현
duckie-team/duckie-android pull request #29
Opened 2022-10-17 17:09 UTC by goddoro

## Overview (Required)

- 스플래쉬, 로그인, 온보딩 화면의 구현을 했습니다.
- 기본적으로 navigator, viewmodel, repository 등 몇 가지 디자인 패턴을 적용했는데 이해가 안되는 부분이 있다면 논의해보면 좋을 듯 합니다.
- 화면이 넘어갈때는 Activity간의 전환으로 구현하였습니다.
- 온보딩 화면의 프로필 기능을 위해 갤러리에서 이미지를 가져오는 로직, 카메라 앱 연동해서 새로 이미지 촬영하는 기능도 들어가있습니다.
- 카카오 로그인은 기본 셋팅만 하고 서버와 연동은 하지 않았습니다.
- 자동 로그인 구현을 위해 PrefUtil과 Holder 패턴을 사용했습니다
- 권한을 PermissionUtil로 delegate했습니다.
- Uri <-> Bitmap 변환을 위해 ImageUtil을 적용했습니다.
- UI 관련된 값들 ( padding, space 등)은 하드코딩으로 적용하였고 추후에 관리하기 좋게 리팩토링 하려고 합니다.

등등 MVP의 구현을 위해 아주 세세적으로는 놓고 간 부분이 많은데 그 부분은 추후에 리팩토링 하는 것으로 결정하고
전체적인 구조에 대해서 같이 얘기를 나눠보면 좋을 것 같습니다.

2022-10-17 17:20 UTC, jisungbin approved these changes
눈에 보이는건 많았는데 차피 MVP 니까 일단 간단간단한 것들만 리뷰했습니다.

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        instance = this
init 시점에는 ApplicationContext 가 초기화되있지 않습니다.
ApplicationContext 초기화 바로 다음으로 onCreate 가 호출됩니다.

참고로 알고계세여

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        lateinit var instance: DuckieApplication
메모리릭 납니당

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
suspendCancellableCoroutine 사용해주세요
로그인 도중에 앱 종료하면 해당 로직을 종료할 방법이 없어서 메모리릭나요

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/DuckieTheme.kt
> +fun DuckieTheme(
요거 꽥꽥 1.2.3 버전에서 추가됐습니다

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/AddTagBottomSheet.kt
> +internal fun AddTagBottomSheetContent(
private?

2022-10-17 17:20 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +    @JvmStatic
Kotlin 100% 인데 필요할까요?

2022-10-17 17:20 UTC, jisungbin commented
작업 수고하셨어요!

2022-10-17 17:24 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        lateinit var instance: DuckieApplication
아 여기 부분 일단 companion object로 빼서 해결을 해야지만 생각해서 어떤식으로 수정하면 좋을까요?

2022-10-17 17:25 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        lateinit var instance: DuckieApplication
해당 값이 어느 파일에서 사용되고 있나요??

2022-10-17 17:26 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        lateinit var instance: DuckieApplication
PrefUtil에서 쓰고 있어요

2022-10-17 17:30 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +        @ApplicationContext
요건 잘못 들어간거 같네여

2022-10-17 17:30 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +object PrefUtil {
얘를 클래스로 만들고 Context 를 inject 받으면 안될까요?
싱글톤으로 provide 해주구요

2022-10-17 17:31 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/application/DuckieApplication.kt
> +        lateinit var instance: DuckieApplication
밑에 추가 코멘트 해드렸습니당

2022-10-17 17:39 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +object PrefUtil {
네 그렇게 할려고 했는데 그러면 object에서 PrefUtil을 사용못하지 않을까요? UserHolder에서 PrefUtil을 사용하고 있어서요

2022-10-17 17:40 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +object PrefUtil {
아 그냥 UserHolder도 singleton으로 inject받을 수 있게 할까 그게 좀 더 낫겠네요..

2022-10-17 17:43 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/PrefUtil.kt
> +object PrefUtil {
그것도 괜찮을거 같아요
오히려 Context 문제 때문에 그게 정답일 수도 있어요

2022-10-17 17:46 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
앱을 종료했는데 메모리 릭을 고려할 필요가 있나요?

2022-10-17 17:49 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
앱을 종료했는데 프로세스가 완전히 종료된게 아니지 않나요? 

```kotlin
companion object {
    val context = applicationContext
}
```

이랑 똑같은 상황 같아요 제 생각엔

2022-10-17 17:56 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
아 네 cancellable하게 바꾸면 좋긴하겠는데 어차피 GC한테 메모리 해제되지 않나요? 앱 종료 이후에 재개했을 때 새로운 Stack에다가 데이터를 쌓으니깐 저게 Activity를 잘 종료했을때랑 뭐가 다를까..싶긴해요.

2022-10-17 17:58 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
GC 가 항상 실행된다는 보장이 있었나요?

2022-10-17 18:00 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
그리고 ViewModelScope안에서 coroutine을 만드는건데도 뷰모델 파괴 이후에 메모리 릭을 고민을 해야할까요? AuthRepository를 가장 상단 Activity에서 ViewModel 없이 사용하는 경우에는 cancellable이 필수적이긴 하겠네요...

2022-10-17 18:01 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
엇 아뇨 GC가 실행은 안되도 Young Generation 범위 안에 걸려있는 상태라 결국엔 JVM이 관리하고 있는애 아닌가해서요.

2022-10-17 18:06 UTC, goddoro commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/AddTagBottomSheet.kt
> +internal fun AddTagBottomSheetContent(
요거 private으로 바꾸면 다른 파일에서 못쓰지 않을까여..?

2022-10-17 18:12 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
> 그리고 ViewModelScope안에서 coroutine을 만드는건데도 뷰모델 파괴 이후에 메모리 릭을 고민을 해야할까요?

이 말씀 듣고 고민을 한 번 더 해봤는데요, 일단 `suspendCoroutine` 은 `Job` 단위가 아니라 `Continuation` 단위로 관리돼서 `viewModelScope` 이랑은 관계가 없어요. `viewModelScope` 은 ViewModel 이 destroy 될 때 연결된 `Job` 을 `cancel` 시켜주는건데, `suspendCoroutine` 은 `Job` 이랑 연결되지 않습니다.

그리고 response 처리의 메모리릭 말고 `Continuation` 의 `complete` 가 destroy 되는 문제도 있는 거 같아요.

2022-10-17 18:18 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/AddTagBottomSheet.kt
> +internal fun AddTagBottomSheetContent(
아하 다른 파일에서도 쓰이는군여 이 파일에서만 쓰이는 줄 알았어요

2022-10-17 18:22 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
> 엇 아뇨 GC가 실행은 안되도 Young Generation 범위 안에 걸려있는 상태라 결국엔 JVM이 관리하고 있는애 아닌가해서요.

GC 는 깊게 공부해보다가 도망쳐서 더 이상은 잘 모르겠네요 ㅠ

2022-10-18 15:46 UTC, riflockle7 requested changes
수고 많으셨습니다. 크래시 우려되는 영역이 하나 있어 Request changes 로 두었습니다.
나머지는 참고만 하시거나, 나중에 반영하셔도 될 것 같습니다.

2022-10-18 15:46 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/gallery/GalleryRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
```kotlin
val images = mutableListOf<MediaStoreImage>()
````
위 부분하고 맨 아래의 return 부분을 withContext 안에 넣고 처리해도 될 것 같은 느낌인데
이건 코드 개선 건이라 나중에 다시 보아도 괜찮을 것 같습니다.

2022-10-18 15:46 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/component/gallery/ImageGalleryActivity.kt
> +                val image = it?.data?.extras?.get("data") as Bitmap
아마 다른 기종에서 data 가 null 이 되는 경우가 있을 것 같은데
null 이 되었을 때 이 코드는 반드시 크래시가 납니다.

`as?` 를 활용하거나 `let` 등을 활용해 null 처리 방법을 다르게 해주는 게 좋을 것 같습니다.

2022-10-18 15:46 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/component/gallery/ImageGalleryActivity.kt
> +                val image = it?.data?.extras?.get("data") as Bitmap
![image](https://user-images.githubusercontent.com/13694046/196476431-de45a19f-9af9-413d-b933-6375bb8d45cd.png)

이건 별개인데 실험하다보니 null 이 반드시 나오는데, null 경고를 하지 않는 무서운 코드가 나올때도 있네요

2022-10-18 15:46 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/util/ImageUtil.kt
> +object ImageUtil {
`context` 를 매개변수로 받는 class 로 처리하면 좋을 것 같네요
hilt 에서 applicationContext 를 주입하는 게 가능했던 것 같은데 (여기에서도 봤던 거 같은데..)
추후에 그걸 활용해서 리펙터링하면 좋을 것 같네요

2022-10-18 16:00 UTC, EvergreenTree97 reviewed
고생 많으셨습니다. 컨플릭 관련해서 회의 나눠봐야 할 것 같네요

2022-10-23 04:36 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
지금 다시 생각해보니 그러면 `suspendCancellableCoroutine` 이랑 `suspendCoroutine` 이랑 왜 구분지어 둔걸까요?

2022-10-23 06:24 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
이렇다고 하네요. 근데 suspendCancellableCoroutine 이 대부분 권장하는 것 같긴하네요
 
![image](https://user-images.githubusercontent.com/13694046/197377375-8fe84426-4fd5-4a65-976f-d0f0768a6504.png)

2022-10-23 06:26 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
아 GlobalScope 를 예시로 드니 이해가 됐네요. 감사해요!
혹시 해당 글 링크 알 수 있을까요? 다시 복습겸 봐보면 좋을거 같네용

2022-10-23 06:29 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
유명한 곳 같긴 해요 여기
https://tourspace.tistory.com/442

2022-10-23 06:40 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/auth/AuthRepositoryImpl.kt
> +        return suspendCoroutine { coroutine ->
아 투덜이님 유명하시져 역시,, 없는게 없군요!
감사합니다!

2022-10-31 16:41 UTC, merged