온보딩 아키텍처 변경
duckie-team/duckie-android pull request #50
Opened 2022-11-15 08:46 UTC by EvergreenTree97

## Overview (Required)
참고: https://github.com/duckie-team/duckie-android/blob/develop/documents/architecture.md#apilibrary

- presentation
    - presentation의 구조를 livedata -> Flow 관리로 변경하였습니다.
    - BaseViewModel을 두어 위 구조를 일반화 하였습니다. 앱 상태는 StateFlow로, SideEffect는 Channel로 관리합니다. 
   
- data
    - local
PrefUtil을 PreferenceDataSource로 이전하였습니다
GalleryRepository를 data로 이전하고 갤러리 가져오는 로직을 Datasource에 구현하였습니다.
    - remote
Kakao 관련 로직을 KaKaoDataSource로 이전하였습니다.
Category get 로직을 UserDataSource로 이전하였습니다.

- domain
    - 각 repository 선언과, usecase를 구현하였습니다.

- 현재 구조에서는 DI를 위해 presentation이 data에 의존성을 가지게 됩니다. 
   domain이 hilt 의존성을 가지거나, DI Module을 따로 빼는 방안이 있습니다.

2022-11-15 09:30 UTC, jisungbin requested changes

2022-11-15 09:30 UTC, jisungbin commented on presentation/src/main/AndroidManifest.xml
>          <activity
`android:configChanges` 정의해주세요
conf change 정책 가져와야 해요

2022-11-15 09:30 UTC, jisungbin commented on presentation/src/main/AndroidManifest.xml
>          <activity
수고하셨습니다.
이거 하나만 반영되면 중요한 문제는 없어보여요

2022-11-15 09:38 UTC, EvergreenTree97 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/LikeCategoryData.kt
> +    val popularTags: List<Tag> = listOf(
Data에서 값을 받을 때는 List형으로 내려오지 않을까 해서요! presentation에서 사용될 때 toPersistentList로 바꿔주는게 나을 것 같다고 생각했습니다

2022-11-15 09:39 UTC, EvergreenTree97 commented on presentation/src/main/AndroidManifest.xml
>          <activity
```android:configChanges 정의해주세요
conf change 정책 가져와야 해요
```
알겠습니당

2022-11-15 09:39 UTC, jisungbin commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/LikeCategoryData.kt
> +    val popularTags: List<Tag> = listOf(
아아 확인헀습니다 👍🏼

2022-11-15 09:42 UTC, EvergreenTree97 commented on presentation/src/main/AndroidManifest.xml
>          <activity
@jisungbin application에 한번만 지정해줘도 상관없나요? 아니면 액티비티마다 지정해야 하나요?
```
<activity
            android:name=".MainActivity"
            android:configChanges="colorMode|uiMode|orientation|screenSize|screenLayout|keyboardHidden|locale|layoutDirection"
            android:exported="true">
```

2022-11-18 16:32 UTC, riflockle7 reviewed
작업하느라 고생 많으셨습니다 🙏
아직 실행은 못해봤고 코드 보면서 눈에 보이는 부분만 comment 남겨 보았습니다.

2022-11-18 16:32 UTC, riflockle7 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/AuthRepositoryImpl.kt
> +            kaKaoDatasource.login(
즉시 취소를 보장하는 `suspendCancellableCoroutine` 을 사용하는 게 더 좋겠습니다.

suspendCoroutine 은 취소 시 코루틴 블록 내 로직이 취소되지 않을 경우가 있습니다.
(ex. withTimeoutOrNull(3000L) 로 3초 뒤에 강제 취소를 의도할 때, suspendCoroutine 을 사용하면 코루틴 블록 로직이 취소 되지 않습니다.)

자세한 내용은 아래 내용을 보면 좋을 것 같습니다,
1. https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html
2. https://tourspace.tistory.com/442

2022-11-18 16:32 UTC, riflockle7 commented on domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/KakaoLoginResponse.kt
> +    val scopes: List<String>? = null,
null 로 처리한 이유가 있을까요? 
나머지 부분은 not null 이어서 궁금했어요

2022-11-18 16:32 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/GalleryScreen.kt
> +
이 부분 예전에 성빈님이 다른걸로 감싸면 coroutineScope 선언 안해도 된다고 들었던 것 같아서요~
한번 확인이 필요해보이네요 (cc. @jisungbin)

2022-11-18 16:32 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryActivity.kt
>                  }
권한 처리 부분도 Screen 영역에 넣으면 좋을 것 같은데 이건 저도 직접 안해봐서 모르겠네요 ㅠ
그거 외에도 중간중간 activity 에서 viewModel 로직 호출하는 건이 있는데, 이건 일단 추후 개선건으로 두면 좋겠네요.
(activity 코드 최대한 줄이기 ㅇㅅㅇ..)

2022-11-18 16:32 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryViewModel.kt
> +        }
실패했을 경우에 따로 처리해줄 내용은 없을까요?
이미지 목록 가져오는 로직인 것 같아서 필요하지 않을까 생각했었네요

2022-11-18 16:32 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/OnboardViewModel.kt
>          }
if 문으로 처리하는 게 더 나을 거 같아요.
when 이 편하긴한데, 중괄호 때문에 코드가 가로로 길어지는 단점이 있다보니
3개 이상 분기 없을때는 if 문이 더 가독성이 깔끔할 것 같아요.

2022-11-18 16:32 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/splash/SplashActivity.kt
> +    }
추후 이것도 1.seconds 로 표현해서 처리하면 더 좋겠네요
개선 사항으로 두시죠

2022-11-18 16:37 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/GalleryScreen.kt
> +
맞아용 `CoroutineScopeContent` 있습니다!

2022-11-18 16:37 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/OnboardViewModel.kt
>          }
오호
전 일부러 다 when 으로 하는 편이긴 해요
if 보단 when 이 더 가독성 좋더라구요 저는 ㅋㅋㅋㅋㅋ

2022-11-18 16:38 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/splash/SplashActivity.kt
> +    }
`1.seconds`

헐 감사합니다 이런게 있었군요!

2022-11-18 16:38 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/splash/SplashActivity.kt
> +    }
아하 근데 제가 원하던거랑은 다르게 `Duration` 반환이군요
까비

2022-11-18 16:56 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/OnboardViewModel.kt
>          }
이건 관점의 차이인 것 같기도 하네요 ㅎㅎ

일단 중괄호가 많아지다보면 가로로 코드가 들여쓰기 한 만큼 길어져서
코드라인 최대 길이를 어겨서 쓸데 없이 2줄로 쓸데도 있어서요

2022-11-18 16:56 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/splash/SplashActivity.kt
> +    }
아아 설명이 짧았네요 ㅎㅅㅎ
확장함수 만들자는 이야기였습니다

2022-11-18 16:59 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/OnboardViewModel.kt
>          }
> 일단 중괄호가 많아지다보면 가로로 코드가 들여쓰기 한 만큼 길어져서
아아 그렇네요

2022-11-18 17:41 UTC, EvergreenTree97 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/GalleryDatasource.kt
>                       */
코드 옮기다가 중복된 것 같습니다 수정하겠슴당

2022-11-18 17:43 UTC, EvergreenTree97 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/AuthRepositoryImpl.kt
> +            kaKaoDatasource.login(
안정성 면에서 `suspendCancellableCoroutine`을 사용하는게 좋겠군요 수정하겠습니다!

2022-11-18 17:45 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/GalleryScreen.kt
> +
@limsaehyun 혹시 이부분 구현하셨다면 체리픽 할 수 있을까요?

2022-11-18 18:14 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryActivity.kt
> +                                )
컨벤션을 확실히 다시 정해야겠네요!

```
isSelected = selectedImages.find { it == item} != null,
```
```
isSelected = selectedImages.find { image: String ->
    image == item
} != null,
```
위와 같은 경우도 오히려 it을 쓰는게 가독성에 더 좋을 것 같아서요!

2022-11-18 18:17 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryActivity.kt
>                  }
override method라 Activity에서 처리할 수 밖에 없을 것 같아요 ㅠ

2022-11-18 18:17 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryViewModel.kt
> +        }
도로님 코드 재구성하는거여서 로직을 자세히 보진 않았는데 한번 고민해보겠습니다!

2022-11-18 18:20 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/onboard/OnboardViewModel.kt
>          }
https://kotlinlang.org/docs/coding-conventions.html#if-versus-when
예전에도 나왔던 주제인데 코틀린 컨벤션에서는 3개 이상일 때 when 문을 지향하긴 해요
그렇지만 저도 when true else 쓰면서 가독성이 좋다고 느꼈슴다

2022-11-18 18:20 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/splash/SplashActivity.kt
> +    }
좋아요~

2022-11-19 10:10 UTC, limsaehyun commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/GalleryScreen.kt
> +
넵!
체리픽을 이러한 경우에 활용하는군요

2022-11-19 10:47 UTC, EvergreenTree97 commented on domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/KakaoLoginResponse.kt
> +    val scopes: List<String>? = null,
```
package com.kakao.sdk.auth.model

@Parcelize
data class OAuthToken(
    val accessToken: String,
    val accessTokenExpiresAt: Date,
    val refreshToken: String,
    val refreshTokenExpiresAt: Date,
    val idToken: String? = null,
    val scopes: List<String>? = null
)
... 
```
Data Layer에서는 OAuthToken이라는 kakao 의존 모델을 사용하는데요, domain에서는 그 의존성을 제거하기 위해 OAuthToken의 프로퍼티를 가지는 KaKaoLoginResponse를 모델로 사용하고 있습니다.
그래서 내부 정의를 그대로 가져와 nullable이 되었습니다

2022-11-19 10:52 UTC, jisungbin approved these changes

2022-11-19 11:34 UTC, riflockle7 commented on domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/KakaoLoginResponse.kt
> +    val scopes: List<String>? = null,
아 kakao 에서 저렇게 제공해주는거군요 이해했습니다!

2022-11-19 11:37 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryActivity.kt
> +                                )
확실히 `it` 강제하기엔 애매한 점이 보이네요
그런데 요건 반점 관련된 리뷰였어서 ~ _ ~ 린트 관련해서 나중에 이야기 나누면 좋을 거 같네요

2022-11-19 11:40 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/common/gallery/ImageGalleryActivity.kt
> +                                )
공감합니다 락스님 

> 확실히 it 강제하기엔 애매한 점이 보이네요

암시적 매개변수가 코틀린 언어의 핵심 기능이라고 저는 생각하는데 이걸 안쓰게 강제하는게 맞나 싶더라구요

2022-11-19 11:41 UTC, riflockle7 approved these changes
나중에 확인 필요할 것 같은 comment 들은 안 접어놨습니다
수고하셨습니다

2022-11-19 11:51 UTC, limsaehyun approved these changes
다른 분들이 리뷰를 너무 잘해주셨네요.
수고하셨어요!

다만, BaseViewModel은 shared 모듈에도 존재해서 둘 중 한 곳에만 위치하면 좋을 것 같아요!

2022-11-19 11:53 UTC, merged