refactor: feature-setting migrate quackv2
duckie-team/duckie-android pull request #500
Opened 2023-05-22 00:24 UTC by limsaehyun

### Issue
* close [feature-setting QuackQuackV2 로 바꾸기](https://www.notion.so/duckie-team/feature-setting-QuackQuackV2-728e9d07de214743956669de6219b259?pvs=4)

### Overview (Required)
* 설정에서 마이그레이션 할 수 있는 부분을 마이그레이션 했습니다.
* QuackQuack V1 to V2

2023-05-23 02:05 UTC, jisungbin requested changes
문법 설탕 적용해 주세요.
문법 설탕이 제대로 지원되는지 검증이 필요합니다.

2023-05-23 14:52 UTC, limsaehyun commented
@jisungbin 반영했습니다! 감사합니다.

2023-05-26 01:10 UTC, limsaehyun commented
@jisungbin 
요거 한 번만 확인 부탁드립니다!

2023-05-27 05:31 UTC, jisungbin approved these changes

2023-05-27 05:31 UTC, merged