시험 상세 서브태그 end쪽에 패딩 없애주기 및 상세화면에 quack v2 적용
duckie-team/duckie-android pull request #529
Opened 2023-06-04 19:25 UTC by riflockle7

## 설명
resolve [시험 상세 서브태그 end쪽에 패딩 없애주기](https://www.notion.so/duckie-team/end-bc2d5450224c407792159260a214fa14?pvs=4)

- 이제 시험 상세 서브태그 우측에 패딩이 없어졌습니다.
- 상세 화면에 quack v2 를 적용하였습니다 (v1 은 제거했습니다)

## 기타
- 변환해보니 빨간줄이 엄청 많네요. (import 및 QuackImage 적용 시 등등)
- QuackCircleTag 는 매치되는 내용을 한참 찾았네요. (style = `QuackTagStyle.Outlined` 을 적용하니 되었습니다)
- common.compose 에서 quack v1 을 쓰고 있어서 그런지 
  ./gradlew build 에서는 잡히지만, IDE 에선 안 보이는 컴파일 에러도 있네요 (빨간줄이 안보입니다)
  ```
  Cannot access class 'kotlinx.collections.immutable.ImmutableList'. Check your module classpath for missing or conflicting dependencies
  ```
  이건 추후 quack v1 을 걷어내면서 해소될 것 같네요

2023-06-04 19:26 UTC, riflockle7 commented on feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/TopCustomBar.kt
>          )
여기입니다

2023-06-05 07:51 UTC, EvergreenTree97 requested changes

2023-06-05 07:51 UTC, EvergreenTree97 commented on feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/quiz/QuizDetailScreen.kt
> +                    text = "${correctProblemCount}덕",
여기 슈가 문법으로 기존처럼 사용하실 수 있어요!
QuackBody2(text = "${correctProblemCount}덕")

2023-06-05 07:52 UTC, EvergreenTree97 commented on feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/TopCustomBar.kt
>          )
어떤 스타일이 어떤 모습인지 볼 수 있으면 좋겠네요

2023-06-05 09:43 UTC, riflockle7 commented on feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/quiz/QuizDetailScreen.kt
> +                    text = "${correctProblemCount}덕",
아아 일부로 최대한 지양했었어요 ㅋㅋ

2023-06-05 09:44 UTC, riflockle7 commented on feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/TopCustomBar.kt
>          )
아 이 컴포저블입니다

<img width="277" alt="image" src="https://github.com/duckie-team/duckie-android/assets/13694046/bc7f6076-933e-478e-8550-95694981e7ed">

2023-06-05 12:59 UTC, merged