앱 설정 구현
duckie-team/duckie-android pull request #53
Opened 2022-11-17 14:16 UTC by limsaehyun

## Issue

- close #52 

## Overview (Required)

[아키텍처 셈플](https://github.com/duckie-team/duckie-android/blob/develop/documents/architecture.md#apilibrary)를 참고했습니다.
- 베이스 작업과, 앱 설정을 작업하였습니다.

### 작업 내용
- 필요한 gradle (KTor, Room)등을 추가하였습니다.

**presentation**
- 베이스 코드 (DI Module, BaseViewModel) 등을 작업했습니다.
- 앱 UI (앱 설정, 앱 계정 정보, 덕키 정보, 라이센스, 알람, 개인정보처리방침, 이용약관), 앱 Navigator작업

**domain**
* SettingRepository interface, UseCase 구현

**data**
* SettingRepositoryImpl, LocalSettingDataSource, RemoteSettingDataSource를 작업했습니다.
* 현재는 RemoteSettingDataSource에서 더미 데이터를 리턴하도록 구현하였습니다.

### 참고
* 초기 작업이라서 PR이 예상 밖으로 커졌습니다 죄송합니다..
* 실수가 많을 것으로 예상됩니다. 날카로운 리뷰 부탁드립니다.
* DI 모듈을 분리하는 작업을 진행해야 합니다.
* 디자인 시스템에서 Switch를 구현해야 합니다. 현재 임시로 Material을 사용 중입니다.
* 디자인 시스템 폰트 이슈가 있습니다.
* 로그아웃, 회원원탈퇴 UI가 아직 디자인 미완입니다.
* 테스트코드, 디테일은 다음 작업에서 진행 할 예정입니다.
* 상록님의 PR과 conflict가 예상됩니다.

## Screenshot
<img src="https://user-images.githubusercontent.com/80076029/202467314-2d8a7a3a-82da-4fe7-acd4-deb2237c4c78.png" width="300" /> | <img src="https://user-images.githubusercontent.com/80076029/202467333-1f53f5f3-5895-4536-8336-ac1d6382bcbe.png" width="300" />
<img src="https://user-images.githubusercontent.com/80076029/202467349-a3466ccd-73d0-4b6b-a59e-3c9e5b82ee49.png" width="300" /> | <img src="https://user-images.githubusercontent.com/80076029/202467358-cc47e598-d89f-4620-88a7-701e059d241f.png" width="300" />
<img src="https://user-images.githubusercontent.com/80076029/202467364-f0e3b542-ce9a-438b-b27f-64879bdfc4ab.png" width="300" /> | <img src="https://user-images.githubusercontent.com/80076029/202467388-93fc0e5e-2b13-45f9-bd8b-a78a2059acb9.png" width="300" />

2022-11-17 14:36 UTC, jisungbin commented
- 디자인 시스템에서 Switch를 구현해야 합니다. 현재 임시로 Material을 사용 중입니다.
- 디자인 시스템 폰트 이슈가 있습니다.

각각 디테일하게 꽥꽥 이슈로 추가해주실 수 있나요? 부탁드릴게요! 그래야 제가 안놓쳐서요 ㅠ

2022-11-17 14:58 UTC, jisungbin requested changes
작업 수고하셨어요!
몇몇 바뀌었으면 하는게 있어서 changes 요청 드립니다.

2022-11-17 14:58 UTC, jisungbin commented on data/build.gradle.kts
> +    add("kapt", Dependencies.Compiler.RoomKsp)
 `kapt` extension 을 안쓰신 이유가 있나요?

2022-11-17 14:58 UTC, jisungbin commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/room/DuckieDataBase.kt
> +    version = 2,
버전 1 부터 시작해야 할 거 같습니다~!

2022-11-17 14:58 UTC, jisungbin commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/room/DuckieDataBase.kt
> +    exportSchema = false,
요긴 왜 false 로 하셨나요?

2022-11-17 14:58 UTC, jisungbin commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/AccountInformationData.kt
> +    val accountType: String,
accountType 에 오타가 발생하기 쉬워 보여요
얘를 들어 `KAKAO` or `Kakao` or `kakao` 등등...

그래서 enum class 로 묶어서 관리하는게 어떨까요?

2022-11-17 14:58 UTC, jisungbin commented on presentation/build.gradle.kts
> +    implementation(project(":data"))
typesafe project accessors 사용 부탁드려요 🙏🏼

2022-11-17 14:58 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/RoomModule.kt
> +    ): DuckieDataBase = Room
그리고 싱글톤으로 설계하셔야 할 듯 합니다
(이미 singleton provides 이긴 하지만 그대로 안전을 위해서요!)

2022-11-17 14:58 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingInquiryScreen.kt
> +    const val email = "duckieteam.hi@gmail.com"
`hi@duckie.team` 으로 바꿔주세용

2022-11-17 14:58 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/utils/AccountType.kt
> +internal fun String.toAccountType(): AccountType =
이 메서드를 따로 만드신 특별한 이유가 있을까요?

2022-11-17 14:58 UTC, jisungbin commented on presentation/src/main/res/values/strings.xml
> +    <string name="log_out">로그아웃</string>
리소스 컨벤션이 있는데 ㅠㅠ
이런거 미리미리 문서화를 안해둔 제 잘못입니당...ㅠ

2022-11-17 14:59 UTC, jisungbin commented
눈에 띄는 부분은 많았지만 미리 문서화를 안해둔 제 잘못이 일부 있는거 같아서 대량 생략하였습니다.
작업 수고하셨어요!

2022-11-17 17:25 UTC, EvergreenTree97 reviewed
GOOD BOY

2022-11-17 17:25 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/MainActivity.kt
> +    lateinit var settingVM: SettingViewModel
이부분은 좀 고민이네요.. Main에서 각 BottomNavigation마다 ViewModel을 가지고 있을텐데 Main에서 Navigation으로 ViewModel을 여러개 넘겨 주는 상황이 발생할 것 같아요

2022-11-17 17:25 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/component/SettingBase.kt
> +private val DP_MAX = 1000.dp
파스칼 케이스로 변경해야 할 것 같습니다!

2022-11-17 17:25 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/component/SettingBase.kt
> +internal fun PaddingQuackBody1(
Column 내에 동일한 간격의 컴포넌트를 배치할 때,
verticalArrangment에 `Alignment.spaceby()` 사용하는 것은 어떨까요?

2022-11-17 17:25 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/mvi/SettingContract.kt
> +    object PostSettingFailed : SettingSideEffect()
네이밍이 좀 더 Event에 가까운 것 같습니다
PostSettingFailed가 발생했을 때, 어떤 SideEffect가 발생하는 지 명시하면 좋을 것 같습니다!
NavigateToMain 이런 방식으로요!

2022-11-17 17:25 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/utils/AccountType.kt
> +        else -> throw IllegalArgumentException()
Effect Kotlin을 인용하면, 결과 부족이 발생할 경우 예외를 throw 하는 것 보다, null이나 Failure를 반환하는 것을 지향하는 게 좋다고 합니다

2022-11-18 05:51 UTC, limsaehyun commented on data/build.gradle.kts
> +    add("kapt", Dependencies.Compiler.RoomKsp)
모두 kapt로 처리하고 정리해두었습니다!

2022-11-18 05:53 UTC, limsaehyun commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/room/DuckieDataBase.kt
> +    exportSchema = false,
스키마를 어디서 사용하는지 모르겠어서 false로 작업을 해두었었어요.
혹시 스키마를 활용하는 곳이 있나요?

2022-11-18 07:26 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/mvi/SettingContract.kt
> +    object PostSettingFailed : SettingSideEffect()
Event가 따로 정의되지 않았기 때문에, ViewModel의 메서드가 이벤트가 될 것 같네요

2022-11-18 16:54 UTC, riflockle7 approved these changes
작업하느라 고생 많으셨습니다 🙏
아직 실행은 못해봤고 코드 보면서 눈에 보이는 부분만 comment 남겨 보았습니다.

2022-11-18 16:54 UTC, riflockle7 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/remote/RemoteSettingDataSourceImpl.kt
> +)
이 값들은 어떤 역할을 하는 변수들일까요?
변수 이름을 보니 var 형태로 관리될 데이터들이 아닌 것 같은데 맞을까요?
임시 처리한 내용이라면 TODO 내용을 추가하는 게 좋겠습니다.

2022-11-18 16:54 UTC, riflockle7 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/data2domain.kt
>      bannedAt = banned_at?.toDate(),
여기는 왜 snake case 일까요 ?_?
백앤드 영역 데이터 클래스여서 그런가 싶기도 하네요

2022-11-18 16:54 UTC, riflockle7 commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/SettingRepositoryImpl.kt
> +    private val isOfflineMode: Boolean,
이 값은 네트워크 상태가 `오프라인 상태인지 아닌지`를 변수로 관리하는 걸까요? 

만약 그렇다면 이 값은 상황에 따라 자주 바뀔 거 같아서 이렇게 변수로 두기엔 위험할 거 같네요
SettingRepository 구현체가 singletone 으로 만들어지는 데, 이 값이 자주 변경되어도 무리가 없을까요?

2022-11-18 16:54 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingPrivacyPolicyScreen.kt
> +    "이용약관입니다"
1줄로 작성이 가능해 보입니다.

2022-11-18 16:54 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingScreen.kt
> +                SettingMainScreen(
```kotlin
SettingStep.SETTING_MAIN_SCREEN -> SettingMainScreen(
```

중괄호를 없애고 위와 같은 형태로 적으면, 중괄호 하나를 줄일 수 있을 것 같아요
코드가 가로로 많이 늘어나는 걸 줄일 수 있을 것 같습니다.

나머지 case 부분도 마찬가지 입니다!

2022-11-18 16:54 UTC, riflockle7 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingTermsScreen.kt
> +            "국무총리는 국무위원의 해임을 대통령에게 건의할 수 있다. 의무교육은 무상으로 한다. 모든 국민은 고문을 받지 아니하며, 형사상 자기에게 불리한 진술을 강요당하지 아니한다. 언론·출판에 대한 허가나 검열과 집회·결사에 대한 허가는 인정되지 아니한다. 대통령은 법률안의 일부에 대하여 또는 법률안을 수정하여 재의를 요구할 수 없다."
이거 `"""` 로 처리하면 좀더 깔끔하게 써질 수 있을 거 같은데... 기억이 가물가물해서 한번 찾아 보시겠어요?

```kotlin
""" 
    abcd
    efghijk 
    lmnop
"""
```

이런 식으로 쓸 수 있을꺼에요

2022-11-18 16:54 UTC, riflockle7 commented on shared/compose/src/main/kotlin/land/sungbin/androidprojecttemplate/shared/compose/extension/CoroutineScopeContent.kt
> +    }.content()
아 https://github.com/duckie-team/duckie-android/pull/50 PR 리뷰할 때 남겼던 게 이거였네요
이 코드가 develop 에 없나보군요 ^_ㅠ

2022-11-18 16:58 UTC, jisungbin commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/SettingRepositoryImpl.kt
> +    private val isOfflineMode: Boolean,
> 만약 그렇다면 이 값은 상황에 따라 자주 바뀔 거 같아서 이렇게 변수로 두기엔 위험할 거 같네요  
> SettingRepository 구현체가 singletone 으로 만들어지는 데, 이 값이 자주 변경되어도 무리가 없을까요?

아하 그렇네요 감사합니다!
제가 그 부분까진 생각을 못 했군요 이런,,

2022-11-18 16:59 UTC, jisungbin commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingTermsScreen.kt
> +            "국무총리는 국무위원의 해임을 대통령에게 건의할 수 있다. 의무교육은 무상으로 한다. 모든 국민은 고문을 받지 아니하며, 형사상 자기에게 불리한 진술을 강요당하지 아니한다. 언론·출판에 대한 허가나 검열과 집회·결사에 대한 허가는 인정되지 아니한다. 대통령은 법률안의 일부에 대하여 또는 법률안을 수정하여 재의를 요구할 수 없다."
> 이거 """ 로 처리하면 좀더 깔끔하게 써질 수 있을 거 같은데... 기억이 가물가물해서 한번 찾아 보시겠어요

맞습니다.
대신 `trimMargin()` or `trimIndent()` 를 해줘야 해요 (물론 선택)

2022-11-19 10:29 UTC, EvergreenTree97 commented on shared/compose/src/main/kotlin/land/sungbin/androidprojecttemplate/shared/compose/extension/CoroutineScopeContent.kt
> +    }.content()
겟또~ 감사합니다

2022-11-19 11:50 UTC, jisungbin approved these changes

2022-11-19 13:08 UTC, limsaehyun commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/utils/AccountType.kt
> +internal fun String.toAccountType(): AccountType =
리뷰 반영하면서 Enum으로 Return받으면서 해당 메서드는 필요 없을 것 같습니다.
제거할게요!

2022-11-19 13:20 UTC, limsaehyun commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/MainActivity.kt
> +    lateinit var settingVM: SettingViewModel
음.. 코드가 좀 지저분해 보일 것 같긴 하네요.
월요일 회의 때 얘기해봐요

2022-11-19 13:29 UTC, limsaehyun commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/component/SettingBase.kt
> +internal fun PaddingQuackBody1(
이 부분에서 클릭 범위를 좀 넓게 주고 싶어서 적용했었어요.

2022-11-19 13:32 UTC, EvergreenTree97 commented on presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/component/SettingBase.kt
> +internal fun PaddingQuackBody1(
아아 클릭 범위 때문이였군요!! 👍

2022-11-19 13:45 UTC, limsaehyun commented on data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/remote/RemoteSettingDataSourceImpl.kt
> +)
임시로 데이터를 반환해주는 데이터들입니다.
정리하고 TODO 처리하겠습니다.

2022-11-19 16:45 UTC, jisungbin commented
@limsaehyun `dependencies` label 을 추가하신 의도가 궁금합니당!

2022-11-20 01:51 UTC, limsaehyun commented
> @limsaehyun `dependencies` label 을 추가하신 의도가 궁금합니당! (이런거 말 예쁘게 어떻게 해야 해요 진짜 ㅠ)

아니에요 ㅋㅋㅋ
Dependency 파일에 변경사항이 생기면 해당 label을 사용하는 것 아닌가요?

2022-11-20 01:53 UTC, limsaehyun commented
@jisungbin @riflockle7 @EvergreenTree97 리뷰 감사합니다 :D
상우님이 남겨주신 Repository 관련 피드백 외에는 모두 반영했습니다!
(해당 부분은 논의가 필요해 보여요)

2022-11-20 02:28 UTC, jisungbin commented
> Dependency 파일에 변경사항이 생기면 해당 label을 사용하는 것 아닌가요?

맞긴 맞는데 사용하는 기준이 달라서 으아 이것도 문서화를 안한 제 잘못입니다 ㅠ

2022-11-20 02:29 UTC, jisungbin commented
다들 확인해주셔서 머지 할게요!

2022-11-20 02:29 UTC, merged